services:
  bot:
    build: .
    environment:
      BOT_TOKEN: 7874319913:AAGiwx2NJfYVHigiu02M1oNYP8AaRCOkzr8
      BOT_ADMIN_ID: [981760042, 1608722917]
      POSTGRES_HOST: manicure-bot-krff.db-msk0.amvera.tech
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_data
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_data
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: