"""date edited

Revision ID: 334ca54f457a
Revises: f0a2fa1d4766
Create Date: 2025-05-10 00:58:54.818414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334ca54f457a'
down_revision: Union[str, None] = 'f0a2fa1d4766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_datetime', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.drop_column('appointments', 'work_time')
    op.drop_column('appointments', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('work_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'end_datetime')
    op.drop_column('appointments', 'start_datetime')
    # ### end Alembic commands ###
