"""worktime add

Revision ID: 6d900f18a991
Revises: b622961ef1df
Create Date: 2025-05-08 21:07:04.072387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision: str = '6d900f18a991'
down_revision: Union[str, None] = 'b622961ef1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_time',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.bulk_insert(
        sa.table('work_time',
                 sa.column('id', sa.Integer()),
                 sa.column('time', postgresql.JSONB())
                 ),
        [
            {'id': 1, 'time': '10:00-11:30'},
            {'id': 2, 'time': '12:00-13:30'},
            {'id': 3, 'time': '14:00-15:30'},
            {'id': 4, 'time': '16:00-17:30'},
            {'id': 5, 'time': '18:00-19:30'},
            {'id': 6, 'time': '20:00-21:30'}
        ]
    )
    op.add_column('appointments', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('appointments', sa.Column('work_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'work_time', ['work_time_id'], ['id'])
    op.drop_column('appointments', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'work_time_id')
    op.drop_column('appointments', 'date')
    op.drop_table('work_time')
    # ### end Alembic commands ###
