"""worktime edited

Revision ID: cd6194007a4b
Revises: 6d900f18a991
Create Date: 2025-05-08 22:31:05.693838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6194007a4b'
down_revision: Union[str, None] = '6d900f18a991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('work_time', sa.String(), nullable=True))
    op.drop_constraint('appointments_work_time_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'work_time_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('work_time_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_work_time_id_fkey', 'appointments', 'work_time', ['work_time_id'], ['id'])
    op.drop_column('appointments', 'work_time')
    # ### end Alembic commands ###
